# Generated by Django 3.0.7 on 2022-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='subject_total_marks',
            field=models.FloatField(default=0),
        ),
    ]
